// How each runtime is launched so that its ONLY route to MCP tools is the Virelune Tool Gateway.
// Verified against Codex 0.161.0: `-c mcp_servers={}` does NOT remove servers from the user's config.toml,
// but a dedicated CODEX_HOME loads none. So Virelune gives Codex its own home under the data folder.
// Codex 0.16x also adds built-in MCP servers and tools through features (e.g. "apps" -> codex_apps), so those
// are switched off on every launch and checked at runtime.
import fs from 'node:fs';
import path from 'node:path';

export const GATEWAY_TOKEN_ENV = 'VILLAGE_GATEWAY_TOKEN';

export type CodexLaunch = { args: string[]; env: Record<string, string | undefined>; codexHome: string; configToml: string };

/**
 * Built-in Codex features that would give Codex tools or data outside the village Tool Gateway. They are on by
 * default in Codex 0.16x (checked with `experimentalFeature/list`); the village switches every one off.
 * "apps" is the one that adds the built-in `codex_apps` MCP server (your ChatGPT connectors) when signed in
 * with ChatGPT.
 */
export const CODEX_DISABLED_FEATURES = ['apps', 'enable_mcp_apps', 'plugins', 'remote_plugin', 'browser_use', 'browser_use_external', 'browser_use_full_cdp_access', 'computer_use', 'in_app_browser', 'skill_mcp_dependency_install'];

/** The only MCP server Codex may load in the village. */
export const CODEX_ALLOWED_MCP_SERVERS = ['village'];

const MANAGED_START = '# >>> Virelune Agent Village (managed: rewritten on every launch, do not edit)';
const MANAGED_END = '# <<< Virelune Agent Village';
// Settings the village owns. Anything else Codex writes (for example the [windows] sandbox setup, or project
// trust entries) is kept exactly as it is.
const OWNED_ROOTS = new Set(['mcp_servers', 'features', 'apps', 'plugins']);

/** The table name a TOML header line opens, e.g. `[mcp_servers.village]` -> "mcp_servers". */
function headerRoot(line: string): string | null {
  const m = line.match(/^\s*\[\[?\s*("?)([A-Za-z0-9_-]+)\1/);
  return m ? m[2] : null;
}

/** A top-level `key = ...` or `key.sub = ...` line -> its first key. */
function keyRoot(line: string): string | null {
  const m = line.match(/^\s*("?)([A-Za-z0-9_-]+)\1\s*(\.|=)/);
  return m ? m[2] : null;
}

/**
 * Merge the village's settings into the village Codex home's config.toml: drop every MCP server, feature, app
 * and plugin setting found there, keep everything else, and append the village block. Idempotent.
 */
export function mergeVillageCodexConfig(existing: string, gatewayUrl: string): string {
  const lines = existing.replace(/\r\n/g, '\n').split('\n');
  const kept: string[] = [];
  let inManaged = false;
  let dropTable = false;
  let inTable = false;
  for (const line of lines) {
    if (line.trim() === MANAGED_START) {
      inManaged = true;
      continue;
    }
    if (inManaged) {
      if (line.trim() === MANAGED_END) inManaged = false;
      continue;
    }
    if (/^\s*#\s*Generated by Virelune Agent Village/.test(line)) continue; // the old V2-2A header
    const root = headerRoot(line);
    if (root) {
      inTable = true;
      dropTable = OWNED_ROOTS.has(root);
      if (!dropTable) kept.push(line);
      continue;
    }
    if (dropTable) continue;
    if (!inTable) {
      const k = keyRoot(line);
      if (k && OWNED_ROOTS.has(k)) continue; // e.g. `features.apps = true` or `mcp_servers = { ... }` at the top
    }
    kept.push(line);
  }
  while (kept.length && !kept[kept.length - 1].trim()) kept.pop();
  const block = [
    MANAGED_START,
    '# Codex in the village may only use the village Tool Gateway. Register other tools as Virelune tool servers.',
    '[features]',
    ...CODEX_DISABLED_FEATURES.map((f) => `${f} = false`),
    '',
    '[mcp_servers.village]',
    `url = ${JSON.stringify(gatewayUrl)}`,
    `bearer_token_env_var = "${GATEWAY_TOKEN_ENV}"`,
    MANAGED_END,
  ];
  return [...(kept.length ? [...kept, ''] : []), ...block, ''].join('\n');
}

/** The command-line overrides every village Codex launch uses (they win over any file). */
export function codexLaunchArgs(gatewayUrl: string): string[] {
  return ['app-server', '-c', `mcp_servers.village.url=${JSON.stringify(gatewayUrl)}`, ...CODEX_DISABLED_FEATURES.flatMap((f) => ['-c', `features.${f}=false`])];
}

/**
 * Launch settings for Codex in the village. Used by the runtime adapter, the doctor, the sandbox setup and
 * `codex:verify`, so all four check and run exactly the same configuration.
 */
export function prepareCodexLaunch(o: { dataDir: string; residentId: string; gatewayUrl: string; token: string; baseEnv: Record<string, string | undefined> }): CodexLaunch {
  const codexHome = path.join(o.dataDir, 'runtime', 'codex-home');
  fs.mkdirSync(codexHome, { recursive: true });
  const url = `${o.gatewayUrl.replace(/\/$/, '')}/mcp/${encodeURIComponent(o.residentId)}`;
  const file = path.join(codexHome, 'config.toml');
  const before = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  const configToml = mergeVillageCodexConfig(before, url);
  if (configToml !== before) fs.writeFileSync(file, configToml);
  // Only pass through what Codex needs; the gateway token travels in an env var, never in files or arguments.
  const env: Record<string, string | undefined> = { ...o.baseEnv, CODEX_HOME: codexHome, [GATEWAY_TOKEN_ENV]: o.token };
  delete env.OPENAI_API_KEY; // Codex uses its own login in the village Codex home, not Echo's key.
  delete env.ANTHROPIC_API_KEY;
  delete env.CODEX_API_KEY; // an API key would bill per token instead of the ChatGPT plan
  delete env.OPENAI_BASE_URL;
  // The resident's gateway URL is also on the command line, so several Codex residents starting at once can
  // share the village Codex home (and its single sign-in) without racing on config.toml.
  return { args: codexLaunchArgs(url), env, codexHome, configToml };
}

/**
 * Ask a running village Codex app-server what it actually loaded. Returns problems (empty = isolated):
 * any MCP server other than the village gateway, or any of the switched-off features still enabled.
 */
export async function checkCodexIsolation(rpc: { request: (m: string, p: any, t?: number) => Promise<any> }): Promise<{ problems: string[]; servers: string[] }> {
  const problems: string[] = [];
  const status = await rpc.request('mcpServerStatus/list', {}, 30_000);
  const servers: string[] = (status?.data ?? []).map((s: any) => String(s.name));
  const extra = servers.filter((n) => !CODEX_ALLOWED_MCP_SERVERS.includes(n));
  if (extra.length) problems.push(`Codex can see MCP servers other than the village gateway: ${extra.join(', ')}`);
  const feats = await rpc.request('experimentalFeature/list', {}, 15_000).catch(() => null);
  if (feats?.data) {
    const on = (feats.data as any[]).filter((f) => CODEX_DISABLED_FEATURES.includes(f.name) && f.enabled).map((f) => f.name);
    if (on.length) problems.push(`Codex features that reach outside the village are still on: ${on.join(', ')}`);
  }
  return { problems, servers };
}

/** Thread settings Village Hall always sends to Codex: workspace-only writes and approvals routed to us. */
export function codexThreadDefaults(cwd: string) {
  return { cwd, sandbox: 'workspace-write' as const, approvalPolicy: 'untrusted' as const };
}

/**
 * Claude Agent SDK options for a resident. strictMcpConfig + settingSources: [] stop the SDK from loading the
 * user's own MCP servers and settings (CLI flags --strict-mcp-config / --setting-sources exist in Claude Code 2.1.42;
 * SDK option behaviour is verified by the Claude adapter test on a machine with the SDK installed).
 */
export function claudeSdkOptions(o: { residentId: string; gatewayUrl: string; token: string; cwd: string; allowShell: boolean }) {
  return {
    cwd: o.cwd,
    permissionMode: 'default',
    settingSources: [] as string[],
    strictMcpConfig: true,
    mcpServers: { village: { type: 'http', url: `${o.gatewayUrl.replace(/\/$/, '')}/mcp/${encodeURIComponent(o.residentId)}`, headers: { Authorization: `Bearer ${o.token}` } } },
    // Specialist residents get no shell at all; general residents get shell only through approvals.
    disallowedTools: o.allowShell ? ['WebFetch', 'WebSearch'] : ['Bash', 'WebFetch', 'WebSearch'],
  };
}
