// How each runtime is launched so that its ONLY route to MCP tools is the Virelune Tool Gateway.
// Verified against Codex 0.161.0: `-c mcp_servers={}` does NOT remove servers from the user's config.toml,
// but a dedicated CODEX_HOME loads none. So Virelune gives Codex its own home under the data folder.
import fs from 'node:fs';
import path from 'node:path';

export const GATEWAY_TOKEN_ENV = 'VILLAGE_GATEWAY_TOKEN';

export type CodexLaunch = { args: string[]; env: Record<string, string | undefined>; codexHome: string; configToml: string };

/** Write the village Codex home's config.toml with only the gateway, and return launch settings. */
export function prepareCodexLaunch(o: { dataDir: string; residentId: string; gatewayUrl: string; token: string; baseEnv: Record<string, string | undefined> }): CodexLaunch {
  const codexHome = path.join(o.dataDir, 'runtime', 'codex-home');
  fs.mkdirSync(codexHome, { recursive: true });
  const url = `${o.gatewayUrl.replace(/\/$/, '')}/mcp/${encodeURIComponent(o.residentId)}`;
  const configToml = [
    '# Generated by Virelune Agent Village. Do not add MCP servers here; register them as Virelune tool servers.',
    '[mcp_servers.village]',
    `url = ${JSON.stringify(url)}`,
    `bearer_token_env_var = "${GATEWAY_TOKEN_ENV}"`,
    '',
  ].join('\n');
  fs.writeFileSync(path.join(codexHome, 'config.toml'), configToml);
  // Only pass through what Codex needs; the gateway token travels in an env var, never in files.
  const env: Record<string, string | undefined> = { ...o.baseEnv, CODEX_HOME: codexHome, [GATEWAY_TOKEN_ENV]: o.token };
  delete env.OPENAI_API_KEY; // Codex uses its own login in the village Codex home, not Echo's key.
  delete env.ANTHROPIC_API_KEY;
  return { args: ['app-server'], env, codexHome, configToml };
}

/** Thread settings Village Hall always sends to Codex: workspace-only writes and approvals routed to us. */
export function codexThreadDefaults(cwd: string) {
  return { cwd, sandbox: 'workspace-write' as const, approvalPolicy: 'untrusted' as const };
}

/**
 * Claude Agent SDK options for a resident. strictMcpConfig + settingSources: [] stop the SDK from loading the
 * user's own MCP servers and settings (CLI flags --strict-mcp-config / --setting-sources exist in Claude Code 2.1.42;
 * SDK option behaviour is verified by the Claude adapter test on a machine with the SDK installed).
 */
export function claudeSdkOptions(o: { residentId: string; gatewayUrl: string; token: string; cwd: string; allowShell: boolean }) {
  return {
    cwd: o.cwd,
    permissionMode: 'default',
    settingSources: [] as string[],
    strictMcpConfig: true,
    mcpServers: { village: { type: 'http', url: `${o.gatewayUrl.replace(/\/$/, '')}/mcp/${encodeURIComponent(o.residentId)}`, headers: { Authorization: `Bearer ${o.token}` } } },
    // Specialist residents get no shell at all; general residents get shell only through approvals.
    disallowedTools: o.allowShell ? ['WebFetch', 'WebSearch'] : ['Bash', 'WebFetch', 'WebSearch'],
  };
}
