// Regressions from the first Windows verification of the Codex adapter (Codex 0.162.0, ChatGPT Plus):
//  1. `codex_apps` (the built-in ChatGPT connectors MCP server) was visible inside the village Codex home.
//  2. The doctor said the Windows sandbox was ready, then the adapter said it was not configured, because the
//     adapter overwrote config.toml and erased the [windows] section the sandbox setup had written.
//  3. `npm run codex:verify` could not delete its temp folder on Windows: Codex was still running inside it.
//  4. The doctor and codex:verify did not launch Codex the way the adapter does.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { test } from 'node:test';
import { CodexAdapter } from '../integrations/adapters/codex.ts';
import { checkCodex } from '../integrations/checks.ts';
import { StdioRpcClient } from '../integrations/jsonrpc-stdio.ts';
import { checkCodexIsolation, CODEX_DISABLED_FEATURES, codexLaunchArgs, mergeVillageCodexConfig, prepareCodexLaunch } from '../integrations/runtime-config.ts';
import { which } from '../integrations/util.ts';
import type { Village } from '../server/lib/app.ts';
import { PROJECT_ROOT } from '../server/lib/config.ts';
import { makeVillage, tmpDir } from './helpers.ts';

const FAKE = path.join(PROJECT_ROOT, 'tests', 'fixtures', 'fake-codex-app-server.ts');
const ALL = ['git', 'node', 'codex', 'openai-api', 'anthropic-api', 'claude-agent-sdk', 'openai-agents', 'ollama', 'blender', 'unreal', 'aura'];
const allReady = () => ALL.map((id) => ({ id, name: id, status: 'connected' as const, ready: true, version: null, summary: 'ok', checks: [], costs: '' }));

function codexVillage(env: Record<string, string>, o: { platform?: NodeJS.Platform; seedConfig?: string } = {}) {
  const log = path.join(tmpDir('virelune-reg-'), 'log.jsonl');
  const made = makeVillage({
    adapters: (v: Village) => {
      if (o.seedConfig !== undefined) {
        const home = path.join(v.config.dataDir, 'runtime', 'codex-home');
        fs.mkdirSync(home, { recursive: true });
        fs.writeFileSync(path.join(home, 'config.toml'), o.seedConfig);
      }
      return [
        new CodexAdapter({
          dataDir: v.config.dataDir,
          env: { PATH: process.env.PATH, SystemRoot: process.env.SystemRoot, FAKE_CODEX_LOG: log, ...env },
          events: v.events,
          approvals: v.approvals,
          issueToken: (id) => v.gateway.issueToken(id),
          revokeToken: (id) => v.gateway.revokeToken(id),
          gatewayUrl: () => 'http://127.0.0.1:4317',
          workspaceFor: (id) => v.workspaceFor(id),
          command: process.execPath,
          commandArgs: ['--disable-warning=ExperimentalWarning', FAKE],
          platform: o.platform,
        }),
      ];
    },
  });
  made.village.setDoctorResultsForTest(allReady());
  const entries = () => (fs.existsSync(log) ? fs.readFileSync(log, 'utf8').trim().split('\n').filter(Boolean).map((l) => JSON.parse(l)) : []);
  return { ...made, entries, log };
}

async function settle(village: Village, resident = 'codex') {
  const t0 = Date.now();
  while (village.chat.isBusy(resident) && Date.now() - t0 < 15_000) await new Promise((r) => setTimeout(r, 15));
  await new Promise((r) => setTimeout(r, 10));
}

// ---------- 2: config.toml is merged, never overwritten ----------

const SANDBOX_SETUP_CONFIG = [
  'model = "gpt-5-codex"',
  'features.apps = true',
  'mcp_servers = { personal = { command = "evil" } }',
  '',
  '# Generated by Virelune Agent Village. Do not add MCP servers here; register them as Virelune tool servers.',
  '[mcp_servers.village]',
  'url = "http://127.0.0.1:4317/mcp/codex"',
  'bearer_token_env_var = "VILLAGE_GATEWAY_TOKEN"',
  '',
  '[windows]',
  'sandbox = "unelevated"',
  '',
  '[projects."C:\\\\Users\\\\me\\\\virelune-sandbox"]',
  'trust_level = "trusted"',
  '',
  '[mcp_servers.personal_files]',
  'command = "npx"',
  'args = ["some-mcp"]',
  '',
  '[features]',
  'apps = true',
  'computer_use = true',
  '',
  '[apps._default]',
  'enabled = true',
  '',
  '[[plugins.installed]]',
  'name = "x"',
  '',
].join('\r\n');

test('config.toml merge keeps what Codex wrote ([windows] sandbox setup, project trust, model) and drops every foreign tool source', () => {
  const out = mergeVillageCodexConfig(SANDBOX_SETUP_CONFIG, 'http://127.0.0.1:4317/mcp/codex');
  assert.match(out, /^\[windows\]\nsandbox = "unelevated"$/m, 'the Windows sandbox setup survives');
  assert.match(out, /^\[projects\."C:\\\\Users\\\\me\\\\virelune-sandbox"\]\ntrust_level = "trusted"$/m);
  assert.match(out, /^model = "gpt-5-codex"$/m);
  assert.doesNotMatch(out, /personal|evil|some-mcp|plugins\.installed|apps\._default/, 'personal MCP servers, apps and plugins are removed');
  assert.doesNotMatch(out, /^features\.apps/m);
  assert.equal((out.match(/^\[mcp_servers\./gm) ?? []).length, 1, 'exactly one MCP server');
  assert.equal((out.match(/^\[features\]/gm) ?? []).length, 1);
  for (const f of CODEX_DISABLED_FEATURES) assert.match(out, new RegExp(`^${f} = false$`, 'm'));
  assert.ok(!out.includes('\r'), 'normalised line endings');
  assert.equal(mergeVillageCodexConfig(out, 'http://127.0.0.1:4317/mcp/codex'), out, 'idempotent');
  const moved = mergeVillageCodexConfig(out, 'http://127.0.0.1:5000/mcp/codex');
  assert.match(moved, /url = "http:\/\/127\.0\.0\.1:5000\/mcp\/codex"/);
  assert.match(moved, /^\[windows\]$/m);
});

test('the Windows sandbox stays ready after the adapter launches Codex (doctor and adapter agree)', async () => {
  // The fake reports "ready" only while the [windows] section is in config.toml, like the real setup.
  const { village, entries } = codexVillage({ FAKE_CODEX_MODE: 'ok', FAKE_WIN_SANDBOX: 'from-config' }, { platform: 'win32', seedConfig: SANDBOX_SETUP_CONFIG });
  try {
    village.chat.send('codex', 'Hello from Windows');
    await settle(village);
    const m = village.chat.list('codex')[1];
    assert.equal(m.status, 'complete', m.reason ?? '');
    assert.ok(entries().some((e) => e.method === 'windowsSandbox/readiness'), 'the adapter really checked readiness');
    const toml = fs.readFileSync(path.join(village.config.dataDir, 'runtime', 'codex-home', 'config.toml'), 'utf8');
    assert.match(toml, /^\[windows\]$/m);
  } finally {
    village.close();
  }
});

test('without the sandbox setup the adapter still refuses on Windows (the check is not weakened)', async () => {
  const { village, entries } = codexVillage({ FAKE_CODEX_MODE: 'ok', FAKE_WIN_SANDBOX: 'from-config' }, { platform: 'win32', seedConfig: '' });
  try {
    village.chat.send('codex', 'Hello');
    await settle(village);
    const m = village.chat.list('codex')[1];
    assert.equal(m.status, 'failed');
    assert.match(m.reason!, /Windows sandbox is not set up/);
    assert.equal(entries().filter((e) => e.method === 'turn/start').length, 0);
  } finally {
    village.close();
  }
});

// ---------- 1: codex_apps and other built-in tool sources ----------

test('codex_apps does not load: the apps feature and other built-in tool sources are switched off on launch', async () => {
  const { village, entries } = codexVillage({ FAKE_CODEX_MODE: 'ok' });
  try {
    village.chat.send('codex', 'Hi');
    await settle(village);
    assert.equal(village.chat.list('codex')[1].status, 'complete');
    const start = entries().find((e) => e.type === 'start');
    for (const f of CODEX_DISABLED_FEATURES) assert.ok(start.argv.includes(`features.${f}=false`), f);
  } finally {
    village.close();
  }
});

test('if Codex still exposes codex_apps or any other MCP server, the adapter refuses before any model request', async () => {
  for (const [env, pattern] of [
    [{ FAKE_FEATURES_FORCED_ON: 'apps' }, /codex_apps.*features that reach outside the village are still on: apps/],
    [{ FAKE_EXTRA_MCP: 'personal_files' }, /MCP servers other than the village gateway: personal_files/],
    [{ FAKE_FEATURES_FORCED_ON: 'computer_use' }, /still on: computer_use/],
  ] as const) {
    const { village, entries } = codexVillage({ FAKE_CODEX_MODE: 'ok', ...env });
    try {
      village.chat.send('codex', 'Hi');
      await settle(village);
      const m = village.chat.list('codex')[1];
      assert.equal(m.status, 'failed');
      assert.match(m.reason!, /Virelune refused to use Codex/);
      assert.match(m.reason!, pattern);
      const methods = entries().filter((e) => e.type === 'request').map((e) => e.method);
      assert.ok(!methods.includes('account/read') && !methods.includes('thread/start') && !methods.includes('turn/start'), `nothing after the isolation check: ${methods.join(', ')}`);
    } finally {
      village.close();
    }
  }
});

// ---------- 3: Codex has exited before cleanup ----------

test('closing the adapter waits until Codex has exited, so its folders can be deleted (Windows EPERM)', async () => {
  const { village, entries } = codexVillage({ FAKE_CODEX_MODE: 'ok' });
  village.chat.send('codex', 'Hi');
  await settle(village);
  const pid = entries().find((e) => e.type === 'start').pid;
  assert.doesNotThrow(() => process.kill(pid, 0), 'Codex is running');
  await village.adapters.get('codex-app-server')!.close!();
  assert.throws(() => process.kill(pid, 0), /ESRCH/, 'Codex has exited when close() resolves');
  fs.rmSync(village.workspaceFor('codex'), { recursive: true });
  village.close();
});

// ---------- 4: the doctor checks the same launch the adapter uses ----------

test('the doctor launches Codex exactly like the adapter (same args, home, environment, workspace) and catches codex_apps', { skip: process.platform === 'win32' ? 'uses a POSIX shell wrapper for the fake Codex' : false }, async () => {
  const dir = tmpDir('virelune-doc-');
  const wrapper = path.join(dir, 'codex');
  fs.writeFileSync(wrapper, `#!/bin/sh\nexec "${process.execPath}" --disable-warning=ExperimentalWarning "${FAKE}" "$@"\n`, { mode: 0o755 });
  const dataDir = path.join(dir, 'data');
  const workspace = path.join(dir, 'workspace');
  const run = async (extra: Record<string, string>) => {
    const log = path.join(dir, `log-${Math.random().toString(36).slice(2)}.jsonl`);
    const res = await checkCodex({ env: { PATH: process.env.PATH, CODEX_PATH: wrapper, FAKE_CODEX_LOG: log, OPENAI_API_KEY: 'sk-test-must-not-reach-codex', ...extra }, projectRoot: PROJECT_ROOT, dataDir, live: true, workspace });
    const entries = fs.readFileSync(log, 'utf8').trim().split('\n').map((l) => JSON.parse(l));
    return { res, entries };
  };
  const ok = await run({ FAKE_CODEX_MODE: 'ok' });
  assert.equal(ok.res.ready, true, ok.res.summary);
  const appServer = ok.entries.find((e) => e.type === 'start' && e.argv.includes('app-server'));
  const expected = prepareCodexLaunch({ dataDir, residentId: 'codex', gatewayUrl: 'http://127.0.0.1:4317', token: 'x', baseEnv: {} });
  assert.deepEqual(appServer.argv.slice(appServer.argv.indexOf('app-server')), expected.args, 'same command line as the adapter');
  assert.deepEqual(appServer.argv.slice(appServer.argv.indexOf('app-server')), codexLaunchArgs('http://127.0.0.1:4317/mcp/codex'));
  assert.equal(appServer.env.CODEX_HOME, path.join(dataDir, 'runtime', 'codex-home'), 'same village Codex home');
  assert.equal(appServer.env.OPENAI_API_KEY, false, 'same stripped environment');
  assert.equal(appServer.cwd, workspace, 'same workspace');
  for (const e of ok.entries.filter((x) => x.type === 'start')) assert.equal(e.env.OPENAI_API_KEY, false, `${e.argv.join(' ')}: no API key, even for --version and login status`);
  assert.ok(ok.res.checks.some((c) => c.name.startsWith('MCP isolation') && c.result === 'pass'));
  const leaky = await run({ FAKE_CODEX_MODE: 'ok', FAKE_FEATURES_FORCED_ON: 'apps' });
  assert.equal(leaky.res.ready, false);
  assert.match(leaky.res.checks.find((c) => c.name.startsWith('MCP isolation'))!.detail, /codex_apps/);
  assert.match(leaky.res.summary, /outside the village gateway/);
});

// Real Codex CLI (skipped when it is not installed): with the village launch settings Codex itself must report
// every built-in tool source switched off and only the village gateway loaded, and keep a [windows] section.
test('real Codex CLI: village launch settings switch off codex_apps and friends and keep the sandbox setup', { skip: which('codex') ? false : 'Codex CLI not installed on this machine', timeout: 120_000 }, async () => {
  const dataDir = tmpDir('virelune-realcodex-');
  const home = path.join(dataDir, 'runtime', 'codex-home');
  fs.mkdirSync(home, { recursive: true });
  fs.writeFileSync(path.join(home, 'config.toml'), SANDBOX_SETUP_CONFIG.replace('[windows]\r\nsandbox = "unelevated"', '[windows]\r\nsandbox = "unelevated"'));
  const launch = prepareCodexLaunch({ dataDir, residentId: 'codex', gatewayUrl: 'http://127.0.0.1:9', token: 'x', baseEnv: { PATH: process.env.PATH, HOME: dataDir, USERPROFILE: dataDir } });
  const rpc = new StdioRpcClient(which('codex')!, launch.args, { env: launch.env, cwd: dataDir });
  rpc.onRequest = () => {
    throw new Error('no');
  };
  try {
    await rpc.request('initialize', { clientInfo: { name: 'virelune-test', title: 'test', version: '1' }, capabilities: null }, 30_000);
    rpc.notify('initialized');
    const iso = await checkCodexIsolation(rpc);
    assert.deepEqual(iso.problems, []);
    assert.deepEqual(iso.servers, ['village']);
    const feats = await rpc.request('experimentalFeature/list', {}, 15_000);
    for (const f of CODEX_DISABLED_FEATURES) {
      const got = feats.data.find((x: any) => x.name === f);
      if (got) assert.equal(got.enabled, false, `${f} is off in the real Codex`);
    }
    assert.match(fs.readFileSync(path.join(home, 'config.toml'), 'utf8'), /^\[windows\]\nsandbox = "unelevated"$/m, 'Codex accepted the merged file and the sandbox setup is still there');
  } finally {
    rpc.close();
    await rpc.exited;
  }
});
